language: rust
cache:
  cargo: true
  directories:
    - wasm

rust:
  - stable
  - beta
  - nightly
  - 1.29.0

# distro: bionic

addons:
  chrome: stable
  apt:
    packages:
      # - clang-9
      # - nodejs
      - binutils-dev
      - libunwind8-dev

jobs:
  include:
    - rust: stable
      env: FUZZ=true
    #- rust: stable
    #  env: WASM=true


script:
  - |
    if [ "$FUZZ" = "true" ]; then
      cd fuzz && cargo test --verbose && ./travis-fuzz.sh;
    elif [ "$WASM" = "true" ]; then
      CARGO_TARGET_DIR=wasm cargo install --verbose --force wasm-pack &&
      sed -i 's/\[lib\]/[lib]\ncrate-type = ["cdylib", "rlib"]/' Cargo.toml &&
      wasm-pack build && wasm-pack test --node
    else
      cargo build --verbose
      cargo test --verbose
      CC=clang-9 cargo build --verbose --features "fuzztarget"
      CC=clang-9 cargo build --verbose --no-default-features
    fi
