name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ serde, std, async ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Feature ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=${{matrix.feature}}
      - name: Defaults + ${{matrix.feature}}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{matrix.feature}}
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ nightly, beta, stable, 1.41.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: All features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets --all-features
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Create dependency
        run: |
          cargo new dep_test
          cd dep_test
          printf 'osbt = { path = ".." }\n\n[workspace]' >> Cargo.toml
      - name: Build dependency
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Clean up
        run: |
          cd ..
          rm -rf dep_test
